# Generated by Django 3.1.1 on 2020-10-03 13:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('damage', models.IntegerField()),
                ('critical', models.IntegerField()),
                ('critical_chance', models.IntegerField()),
                ('is_zone', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('special_effect', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('life_point', models.IntegerField()),
                ('damage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('is_special', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('nb_room', models.IntegerField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SessionCharacters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('life_point', models.IntegerField()),
                ('max_life_point', models.IntegerField()),
                ('level', models.IntegerField(default=1)),
                ('is_alive', models.BooleanField(default=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.character')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.session')),
            ],
        ),
        migrations.CreateModel(
            name='TypeAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='SessionCharactersAttacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_bonuses', models.IntegerField(default=0, null=True)),
                ('attack', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.attacks')),
                ('session_character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.sessioncharacters')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.user'),
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_round', models.IntegerField(default=1, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomMonster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('life_point_left', models.IntegerField(null=True)),
                ('monster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.monster')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.session'),
        ),
        migrations.CreateModel(
            name='Bonuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('add_attack', models.IntegerField(default=10, null=True)),
                ('type_attack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.typeattack')),
            ],
        ),
        migrations.AddField(
            model_name='attacks',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.character'),
        ),
        migrations.AddField(
            model_name='attacks',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.typeattack'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_monster_turn', models.BooleanField(default=False)),
                ('damage', models.IntegerField(null=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.monster')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.round')),
                ('session_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.sessioncharacters')),
                ('session_character_attack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.sessioncharactersattacks')),
            ],
        ),
    ]
